import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Mitr } from 'next/font/google'
import "./globals.css";
const mitr = Mitr({
  subsets: ['thai'],
  weight: ['200', '300', '400', '500', '600', '700'],
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="th">
      <body className={`${mitr.className} antialiased`}>
        {children}
      </body>
    </html>
  )
}
